### ISSUE TITLE
"formr_items" throws "Error in seq.default(from, to, by) : wrong sign in 'by' argument"

### ISSUE THREAD

**Issue by psycaroly** [rubenarslan/formr#14]
Hi,

I wanted to run the "formr_items" command, so
1. I logged in with `formr_connect("my login", "my password")`. This works, because I can run `formr_raw_results("my survey")` without problems.
2. When I run `formr_items("my survey")` I get the following error:

`Error in seq.default(from, to, by) : wrong sign in 'by' argument`

So I tried to additionally specify the path to the json file, but this did not work either (same error).

What could be the problem?

**Comment by rubenarslan** [comment]
did this work previously? I think you have items that go from 5 to 1 or so, right?

**Comment by psycaroly** [comment]
No, I tried the `formr_results()` function the first time (previously I only used `formr_raw_results()`). When it didn't work I discovered that `formr_items()` was the culprit.

Yes, I have items that go from 5 to 1. Might that be the problem? If so, what can I do about that?

**Comment by rubenarslan** [comment]
You can look at the code of the formr_items function and fix the error. Or
you can wait for me to fix it, probably tomorrow.

**Comment by rubenarslan** [comment]
should be fixed if you reinstall

**Comment by psycaroly** [comment]
Hi Ruben, thank you that you looked into it so fast. It works now!

**Comment by rubenarslan** [comment]
Great! Let me know if the codebook also works for you: https://cran.r-project.org/web/packages/codebook/index.html
