### ISSUE TITLE
Warning message rlang 0.3.0

### ISSUE THREAD

**Issue by selinakreinhard** [rubenarslan/formr#17]
I get the following warning message when I set tag_missings = T. Feel free to use the login data I sent you to reproduce this.
formr_results(survey_name = "ISPT_start", tag_missings = T)

Warning message:
Prefixing `UQS()` with the rlang namespace is deprecated as of rlang 0.3.0.
Please use the non-prefixed form or `!!!` instead.

  # Bad:
  rlang::expr(mean(rlang::UQS(args)))

  # Ok:
  rlang::expr(mean(UQS(args)))

  # Good:
  rlang::expr(mean(!!!args))

**Comment by rubenarslan** [comment]
Are you sure you're using the most recent version (0.7.6)?

**Comment by selinakreinhard** [comment]
you are right, I did not use the latest version. sorry, I'll check this next time beforehand.
