### ISSUE TITLE
formr_results loads false(?) recoded data

### ISSUE THREAD

**Issue by selinakreinhard** [rubenarslan/formr#19]
I get different data with the same column name depending on whether I download data via formr_results or manually from formr.org

if data is downloaded via formr_results:
cor(data$SIS_C_2, data$SIS_C_5R, use="pair") -> positive value (not expected)

if data is downloaded from formr.org manually:
cor(data_formrresult$SIS_C_2, dataformrresult$SIS_C_5R, use="pair") -> negative value (expected)

I assume items with R at the end get recoded by formr_aggregate if a scale was not build due to non-consecutive numbers (e.g. item2, item5R, but not item3 and item4 ).

**Comment by rubenarslan** [comment]
You can download the raw data from formr manually using `formr_raw_results`. Then, you can select which cleaning/helper steps you want.

Yes, item reversion and scale aggregation are separate steps. You are saying, we should not reverse items, unless they are part of a scale?

**Comment by selinakreinhard** [comment]
Nope, but if you reverse items, I would expect their name to change
Based on the description "Example: If your data contains Extraversion_1, Extraversion_2R and Extraversion_3, there will be two new variables in the result: Extraversion_2 (reversed to align with _1 and _2) and Extraversion, the mean score of the three." I did assume that SIS_C_5R is not recoded.

**Comment by rubenarslan** [comment]
Then I need to change the docs. Since we now used labelled values I'm
changing the underlying values but keeping the labels. It's documented in
the codebook paper, apparently I didn't update docs in other places.
