### ISSUE TITLE
Bug: not changing skipping position automatically in waiting module when importing

### ISSUE THREAD

**Issue by Tschulie** [rubenarslan/formr#24]
Typically, all position numbers will be updated automatically when importing a run as JSON file. This includes all skips, position numbers etc. 

But when importing a waiting module, the skip to position number will not be updated and stays identically to the former run's numbers. It would be great if this could be updated automatically too (like all other modules).

**Comment by rubenarslan** [comment]
closed in https://github.com/rubenarslan/formr.org/issues/454
