### ISSUE TITLE
Bug: Login with email and pwd

### ISSUE THREAD

**Issue by bpiskernik** [rubenarslan/formr#37]
Currently, that login with email and pwd does not work  because as far as I can tell the flow control  in `formr_connect()` is broken. IMO `if (!missing(keyring) || is.null(keyring))`  should be replaced with `if (!missing(keyring) || !is.null(keyring))`.

**Comment by adrian-gadient** [comment]
After updating to a new formr version (0.10.1), I am not able anymore to connect to formr using email and password, although I'm using code that was working before. 

Code:

`formr::formr_connect(email=credentials$email, password=credentials$password, host = "https://formr.org")`

The error message is ´Error: service must be a non-empty string (length 1 character)´.
