### ISSUE TITLE
Offering version V9

### ISSUE THREAD

**Issue by adrian-gadient** [rubenarslan/formr#38]
After realising my code doesn't work with the V10, I tried to re-install v9. However, in the release history I cannot find versions between v7.4 and v10. Would it be possible to make v9 available for installation?

**Comment by rubenarslan** [comment]
Sorry, I've not been consistent about tagging releases. You should be able to install a specific commit?
https://github.com/rubenarslan/formr/commit/31293f62eb25ebce451dddc55a79e9f20a38f402

But I would recommend fixing your code, it can't be too hard, and there were bug fixes from 0.9 to 0.10

**Comment by adrian-gadient** [comment]
Good idea, I never tried to install a specific commit. 

I agree, it would make more sense to "fix" the code. However, I'm not sure there is much I can do on my side. #37 suggests that there is a problem when I don't use keyring and it seems this hasn't been fixed yet. Is it still possible to connect without using keyring? Then I'm happy to "fix" the code.

**Comment by rubenarslan** [comment]
Here's an idea: I fix my code, like I should have done when the issue was raised. Sorry, just forgot. Just install the newest version now.

**Comment by adrian-gadient** [comment]
Thank you very much for fixing the code. Everything works correctly again.
